# Generated by Django 5.0.6 on 2024-07-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
