# Generated by Django 5.0.6 on 2024-07-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_purchase_purchase_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_quantity',
        ),
    ]
